steps:
  - label: "Build and Upload Artifact"
    command: |
      cd hello
      go build -o ./my-hello-app
    key: "build-step"
    artifact_paths: "hello/my-hello-app"
  - input: "Get User Name"
    fields:
      - text: "Please Input Your Name"
        key: "name"
    key: "input-step"
    depends_on: ["build-step"]
  - label: "Execution"
    command: |
      .buildkite/execution.sh
      buildkite-agent artifact download hello/my-hello-app . --step build-step
      cd hello
      chmod +x ./my-hello-app
      ./my-hello-app "$(buildkite-agent meta-data get name)"
    key: "execution-step"
    depends_on: ["input-step"]
